server:
  web_port: 10086
  mode: debug
  logfile_dir: ./logs/

jwt:
  jwt_secret: x20SDx3c
  jwt_access_token_expired: 240
  jwt_refresh_token_expired: 300

mysql:
  hostname: 127.0.0.1
  port: 3306
  username: admin
  password: 12345
  db: db_chatroom

redis:
  hostname: 127.0.0.1
  port: 6379
  password:
  db: 0
  cluster_enable: false
  cluster_ips:
    - 127.0.0.1:6381
    - 127.0.0.1:6382
    - 127.0.0.1:6383
